/** Verifix catalog → Prisma delegate map (CRUD resources). */
export type CatalogResource = {
  key: string;
  section: 'hr' | 'attendance' | 'payroll' | 'reports' | 'settings' | 'org';
  title: string;
  /** Prisma client property name */
  model: string;
  /** Default orderBy */
  orderBy?: Record<string, 'asc' | 'desc'>;
  include?: Record<string, unknown>;
  /** Fields accepted on create/update (others stripped) */
  fields: string[];
  /** Soft filter: only active rows when list?active=1 */
  activeField?: string;
};

export const CATALOG_RESOURCES: CatalogResource[] = [
  // —— Org / HR structure ——
  {
    key: 'division-groups',
    section: 'org',
    title: 'Группы отделов',
    model: 'divisionGroup',
    orderBy: { name: 'asc' },
    fields: ['code', 'name', 'isActive', 'createdAt'],
    activeField: 'isActive',
    include: { _count: { select: { divisions: true } } },
  },
  {
    key: 'position-groups',
    section: 'org',
    title: 'Группа должностей',
    model: 'positionGroup',
    orderBy: { name: 'asc' },
    fields: ['code', 'name', 'isActive', 'createdAt'],
    activeField: 'isActive',
    include: { _count: { select: { positions: true } } },
  },
  {
    key: 'position-templates',
    section: 'org',
    title: 'Шаблоны должностей',
    model: 'positionTemplate',
    orderBy: { createdAt: 'desc' },
    include: {
      division: { select: { id: true, code: true, name: true } },
      position: { select: { id: true, code: true, name: true } },
      grade: { select: { id: true, code: true, name: true } },
      schedule: { select: { id: true, code: true, name: true } },
      tariffGroup: { select: { id: true, code: true, name: true } },
    },
    fields: [
      'code',
      'divisionId',
      'positionId',
      'gradeId',
      'scheduleId',
      'tariffGroupId',
      'scheduleItems',
      'accruals',
      'deductions',
      'isActive',
    ],
    activeField: 'isActive',
  },
  {
    key: 'grades',
    section: 'org',
    title: 'Разряды',
    model: 'grade',
    orderBy: { level: 'asc' },
    fields: ['code', 'name', 'level', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'grade-history',
    section: 'hr',
    title: 'Повышение разрядов',
    model: 'gradePromotion',
    orderBy: { documentDate: 'desc' },
    include: {
      division: { select: { id: true, code: true, name: true } },
      lines: {
        orderBy: { sortOrder: 'asc' },
        include: {
          employee: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              middleName: true,
              tabNumber: true,
            },
          },
          fromGrade: { select: { id: true, code: true, name: true } },
          toGrade: { select: { id: true, code: true, name: true } },
          staffPosition: { select: { id: true, code: true, title: true } },
        },
      },
    },
    fields: [
      'documentDate',
      'documentNumber',
      'divisionId',
      'note',
      'periodType',
      'medicalExam',
      'useGphPeriod',
      'assignTraining',
      'status',
    ],
  },
  {
    key: 'grade-recommendations',
    section: 'hr',
    title: 'Рекомендуемый список сотрудников',
    model: 'gradePromotionRecommendation',
    orderBy: { recommendedAt: 'desc' },
    include: {
      employee: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
        },
      },
      grade: { select: { id: true, code: true, name: true } },
      division: { select: { id: true, code: true, name: true } },
      position: { select: { id: true, code: true, name: true } },
    },
    fields: [
      'employeeId',
      'gradeId',
      'divisionId',
      'positionId',
      'recommendedAt',
      'status',
      'note',
    ],
  },
  {
    key: 'career-paths',
    section: 'org',
    title: 'Карьерный путь',
    model: 'careerPath',
    orderBy: { sortOrder: 'asc' },
    include: {
      steps: {
        include: {
          position: true,
          grade: true,
          fromGrade: { select: { id: true, code: true, name: true } },
          toGrade: { select: { id: true, code: true, name: true } },
        },
        orderBy: { sortOrder: 'asc' },
      },
      _count: { select: { steps: true } },
    },
    fields: ['code', 'name', 'sortOrder', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'career-steps',
    section: 'org',
    title: 'Карьерный путь — шаги',
    model: 'careerPathStep',
    orderBy: { sortOrder: 'asc' },
    include: {
      careerPath: true,
      fromGrade: true,
      toGrade: true,
      position: true,
      grade: true,
    },
    fields: [
      'careerPathId',
      'positionId',
      'gradeId',
      'fromGradeId',
      'toGradeId',
      'title',
      'sortOrder',
      'minMonths',
      'attempts',
      'periodMonths',
      'penaltyPeriodMonths',
      'conditions',
    ],
  },
  {
    key: 'tariff-groups',
    section: 'org',
    title: 'Тарифные группы',
    model: 'tariffGroup',
    orderBy: { name: 'asc' },
    include: { grade: true },
    fields: ['code', 'name', 'fullName', 'gradeId', 'baseRate', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'tariff-approvals',
    section: 'org',
    title: 'Утверждения тарифных групп',
    model: 'tariffGroupApproval',
    orderBy: { createdAt: 'desc' },
    include: { tariffGroup: true },
    fields: [
      'tariffGroupId',
      'documentDate',
      'documentNumber',
      'effectiveAt',
      'baseRate',
      'linkedToBase',
      'indicators',
      'lines',
      'status',
      'note',
      'reviewedBy',
      'reviewedAt',
    ],
  },
  {
    key: 'staff-positions',
    section: 'org',
    title: 'Позиции (штат)',
    model: 'staffPosition',
    orderBy: { code: 'asc' },
    include: {
      division: { select: { id: true, code: true, name: true } },
      position: { select: { id: true, code: true, name: true } },
      grade: { select: { id: true, code: true, name: true } },
      tariffGroup: { select: { id: true, code: true, name: true } },
      schedule: { select: { id: true, code: true, name: true } },
      employees: {
        where: { status: 'active' },
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
        },
        take: 20,
      },
    },
    fields: [
      'code',
      'title',
      'divisionId',
      'positionId',
      'tariffGroupId',
      'gradeId',
      'scheduleId',
      'headcount',
      'openedAt',
      'closedAt',
      'vacationDays',
      'roles',
      'groupName',
      'accessDivisionIds',
      'isPrimary',
      'contractualSalary',
      'accruals',
      'deductions',
      'extraInfo',
      'status',
      'isActive',
    ],
    activeField: 'isActive',
  },
  {
    key: 'dismissal-reasons',
    section: 'hr',
    title: 'Причины увольнения',
    model: 'dismissalReason',
    orderBy: { name: 'asc' },
    fields: ['code', 'name', 'groupName', 'basisType', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'clearance-templates',
    section: 'hr',
    title: 'Шаблоны обходных листов',
    model: 'clearanceTemplate',
    orderBy: { createdAt: 'desc' },
    include: {
      division: { select: { id: true, name: true, code: true } },
      position: { select: { id: true, name: true, code: true } },
      employees: {
        orderBy: { sortOrder: 'asc' },
        include: {
          employee: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              middleName: true,
              tabNumber: true,
            },
          },
        },
      },
      items: { orderBy: { sortOrder: 'asc' } },
    },
    fields: [
      'code',
      'name',
      'divisionId',
      'positionId',
      'requireManagerSign',
      'requireHigherManagerSign',
      'isActive',
    ],
    activeField: 'isActive',
  },
  {
    key: 'clearance-sheets',
    section: 'hr',
    title: 'Обходные листы',
    model: 'clearanceSheet',
    orderBy: { documentDate: 'desc' },
    include: {
      employee: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
        },
      },
      template: true,
      items: { orderBy: { sortOrder: 'asc' } },
    },
    fields: [
      'employeeId',
      'templateId',
      'number',
      'documentDate',
      'title',
      'status',
      'note',
      'completedAt',
    ],
  },
  {
    key: 'incident-types',
    section: 'hr',
    title: 'Типы инцидента',
    model: 'incidentType',
    orderBy: { name: 'asc' },
    fields: ['code', 'name', 'accrualName', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'incidents',
    section: 'hr',
    title: 'Инциденты',
    model: 'incident',
    orderBy: { occurredAt: 'desc' },
    include: {
      employee: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
        },
      },
      manager: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
        },
      },
      incidentType: true,
    },
    fields: [
      'employeeId',
      'managerId',
      'incidentTypeId',
      'number',
      'title',
      'description',
      'note',
      'severity',
      'status',
      'action',
      'damageAmount',
      'sendNotification',
      'occurredAt',
      'resolvedAt',
      'resolution',
      'attachments',
    ],
  },
  {
    key: 'gph-contracts',
    section: 'hr',
    title: 'Договор ГПХ',
    model: 'gphContract',
    orderBy: { startDate: 'desc' },
    include: {
      employee: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
          personId: true,
          divisionId: true,
          person: {
            select: { id: true, firstName: true, lastName: true, middleName: true },
          },
          division: { select: { id: true, name: true, code: true } },
        },
      },
      division: { select: { id: true, name: true, code: true } },
      person: {
        select: { id: true, firstName: true, lastName: true, middleName: true },
      },
      services: true,
    },
    fields: [
      'employeeId',
      'divisionId',
      'personId',
      'number',
      'title',
      'startDate',
      'endDate',
      'amount',
      'allowAddService',
      'status',
      'isActive',
      'note',
    ],
    activeField: 'isActive',
  },
  {
    key: 'gph-services',
    section: 'payroll',
    title: 'Список услуг договора ГПХ',
    model: 'gphService',
    orderBy: { createdAt: 'desc' },
    include: {
      contract: {
        include: {
          division: { select: { id: true, name: true, code: true } },
          person: {
            select: { id: true, firstName: true, lastName: true, middleName: true },
          },
          employee: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              middleName: true,
              tabNumber: true,
              person: {
                select: { id: true, firstName: true, lastName: true, middleName: true },
              },
              division: { select: { id: true, name: true, code: true } },
            },
          },
        },
      },
    },
    fields: ['contractId', 'code', 'name', 'unitPrice', 'unit', 'month', 'status', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'name-changes',
    section: 'hr',
    title: 'Реестр изменения имени',
    model: 'employeeNameChange',
    orderBy: { effectiveAt: 'desc' },
    include: {
      employee: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
        },
      },
    },
    fields: [
      'employeeId',
      'oldLastName',
      'oldFirstName',
      'oldMiddleName',
      'newLastName',
      'newFirstName',
      'newMiddleName',
      'effectiveAt',
      'documentNumber',
      'note',
      'status',
    ],
  },
  {
    key: 'wage-changes',
    section: 'hr',
    title: 'Все изменения в оплате труда',
    model: 'wageChange',
    orderBy: { effectiveAt: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
    },
    fields: [
      'employeeId',
      'oldAmount',
      'newAmount',
      'effectiveAt',
      'reason',
      'documentNumber',
      'status',
    ],
  },
  {
    key: 'location-types',
    section: 'attendance',
    title: 'Типы локаций',
    model: 'locationType',
    orderBy: { name: 'asc' },
    fields: ['code', 'name', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'timesheet-adjustments',
    section: 'hr',
    title: 'Корректировки табеля',
    model: 'timesheetCorrection',
    orderBy: { documentDate: 'desc' },
    include: {
      division: { select: { id: true, name: true, code: true } },
      lines: {
        orderBy: { sortOrder: 'asc' },
        include: {
          employee: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              middleName: true,
              tabNumber: true,
              divisionId: true,
            },
          },
        },
      },
    },
    fields: [
      'documentDate',
      'number',
      'title',
      'divisionId',
      'periodFrom',
      'periodTo',
      'meta',
      'status',
    ],
  },
  {
    key: 'schedule-shifts',
    section: 'attendance',
    title: 'Список смен расписания',
    model: 'scheduleShift',
    orderBy: { code: 'asc' },
    include: { schedule: true },
    fields: ['scheduleId', 'code', 'name', 'startTime', 'endTime', 'weekday', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'schedule-overrides',
    section: 'attendance',
    title: 'Индивидуальные графики',
    model: 'individualSchedule',
    orderBy: { documentDate: 'desc' },
    include: {
      division: { select: { id: true, name: true, code: true } },
      lines: {
        include: {
          employee: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              middleName: true,
              tabNumber: true,
              divisionId: true,
              positionId: true,
              position: { select: { id: true, name: true } },
            },
          },
        },
        orderBy: { sortOrder: 'asc' },
      },
    },
    fields: [
      'documentDate',
      'number',
      'month',
      'kind',
      'divisionId',
      'note',
      'verified',
      'settings',
      'normDays',
      'normHours',
      'status',
    ],
  },
  {
    key: 'rosters',
    section: 'attendance',
    title: 'Расписание',
    model: 'workRoster',
    orderBy: { documentDate: 'desc' },
    include: {
      schedule: { select: { id: true, name: true, code: true, kind: true } },
      lines: {
        include: {
          employee: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              middleName: true,
              tabNumber: true,
              positionId: true,
              position: { select: { id: true, name: true } },
            },
          },
        },
        orderBy: { sortOrder: 'asc' },
      },
    },
    fields: [
      'name',
      'documentDate',
      'number',
      'month',
      'scheduleId',
      'note',
      'verified',
      'status',
    ],
  },
  {
    key: 'position-schedules',
    section: 'attendance',
    title: 'Индивидуальные графики для позиций',
    model: 'positionScheduleDoc',
    orderBy: { documentDate: 'desc' },
    include: {
      division: { select: { id: true, name: true, code: true } },
      lines: {
        include: {
          position: { select: { id: true, name: true, code: true } },
          staffPosition: { select: { id: true, code: true, title: true } },
          employee: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              middleName: true,
              tabNumber: true,
              divisionId: true,
              positionId: true,
            },
          },
        },
        orderBy: { sortOrder: 'asc' },
      },
    },
    fields: [
      'documentDate',
      'number',
      'month',
      'kind',
      'divisionId',
      'note',
      'verified',
      'settings',
      'normDays',
      'normHours',
      'status',
    ],
  },
  {
    key: 'internal-trips',
    section: 'attendance',
    title: 'Внутренняя командировка',
    model: 'internalTrip',
    orderBy: { createdAt: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
      location: true,
      recipientDivision: true,
      senderDivision: true,
      position: true,
    },
    fields: [
      'employeeId',
      'recipientDivisionId',
      'senderDivisionId',
      'locationId',
      'positionId',
      'title',
      'startDate',
      'endDate',
      'requestStatus',
      'status',
      'note',
    ],
  },
  {
    key: 'gps-tracks',
    section: 'attendance',
    title: 'Отслеживание местоположения',
    model: 'gpsTrackPoint',
    orderBy: { recordedAt: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
    },
    fields: ['employeeId', 'latitude', 'longitude', 'accuracyM', 'recordedAt', 'source'],
  },
  {
    key: 'payment-orders',
    section: 'payroll',
    title: 'Поручения',
    model: 'paymentOrder',
    orderBy: { startDate: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
    },
    fields: [
      'employeeId',
      'number',
      'title',
      'accrualName',
      'amount',
      'startDate',
      'endDate',
      'dueDate',
      'status',
      'note',
    ],
  },
  {
    key: 'account-pairs',
    section: 'payroll',
    title: 'Парные счета',
    model: 'accountPair',
    orderBy: { code: 'asc' },
    fields: ['code', 'name', 'debitAccount', 'creditAccount', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'settlements',
    section: 'payroll',
    title: 'Взаиморасчеты',
    model: 'settlement',
    orderBy: { createdAt: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
      accountPair: true,
    },
    fields: ['employeeId', 'accountPairId', 'title', 'amount', 'status', 'settledAt', 'note'],
  },
  {
    key: 'sales-policies',
    section: 'payroll',
    title: 'Настройка процентов продаж',
    model: 'salesCommissionPolicy',
    orderBy: { createdAt: 'asc' },
    include: { position: { select: { id: true, name: true, code: true } } },
    fields: ['positionId', 'personalPercent', 'divisionPercent', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'sales-accruals',
    section: 'payroll',
    title: 'Начисления процентов от продаж',
    model: 'salesCommissionAccrual',
    orderBy: { docDate: 'desc' },
    include: {
      division: { select: { id: true, name: true, code: true } },
      position: { select: { id: true, name: true, code: true } },
      lines: {
        include: {
          employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
          position: { select: { id: true, name: true, code: true } },
        },
        orderBy: { sortOrder: 'asc' },
      },
    },
    fields: [
      'number',
      'docDate',
      'periodFrom',
      'periodTo',
      'title',
      'paymentType',
      'salesKind',
      'divisionId',
      'positionId',
      'cashbox',
      'bankAccount',
      'rounding',
      'note',
      'totalSales',
      'totalAmount',
      'status',
    ],
  },
  {
    key: 'loans',
    section: 'payroll',
    title: 'Займы',
    model: 'employeeLoan',
    orderBy: { loanDate: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
      payments: true,
    },
    fields: [
      'number',
      'loanDate',
      'contractNumber',
      'contractDate',
      'employeeId',
      'principal',
      'remaining',
      'monthlyPayment',
      'startDate',
      'endDate',
      'currency',
      'status',
      'note',
    ],
  },
  {
    key: 'loan-payments',
    section: 'payroll',
    title: 'Займы — платежи',
    model: 'loanPayment',
    orderBy: { paidAt: 'desc' },
    fields: ['loanId', 'amount', 'paidAt', 'note'],
  },
  {
    key: 'travel-expenses',
    section: 'payroll',
    title: 'Авансовый отчет по командировке',
    model: 'travelExpenseReport',
    orderBy: { docDate: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
      trip: true,
      lines: true,
    },
    fields: [
      'number',
      'docDate',
      'employeeId',
      'tripId',
      'currency',
      'advance',
      'amount',
      'calcForSalary',
      'status',
      'note',
    ],
  },
  {
    key: 'bonus-accruals',
    section: 'payroll',
    title: 'Бонусные начисления',
    model: 'bonusAccrualDoc',
    orderBy: { docDate: 'desc' },
    include: {
      division: { select: { id: true, name: true, code: true } },
      factType: { select: { id: true, name: true } },
      lines: {
        include: {
          employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
        },
        orderBy: { sortOrder: 'asc' },
      },
    },
    fields: [
      'kind',
      'number',
      'docDate',
      'startDate',
      'endDate',
      'divisionId',
      'factTypeId',
      'factTypeName',
      'considerPayroll',
      'note',
      'totalAmount',
      'status',
    ],
  },
  {
    key: 'candidates',
    section: 'hr',
    title: 'Кандидаты',
    model: 'candidate',
    orderBy: { createdAt: 'desc' },
    include: { staffPosition: true },
    fields: [
      'staffPositionId',
      'fullName',
      'phone',
      'email',
      'status',
      'note',
      'introducedAt',
      'category',
      'education',
      'employmentSource',
      'birthDate',
      'gender',
      'languages',
      'positionName',
      'personType',
    ],
  },
  {
    key: 'vacancies',
    section: 'hr',
    title: 'Вакансии',
    model: 'vacancy',
    orderBy: { openedAt: 'desc' },
    include: { staffPosition: true },
    fields: ['staffPositionId', 'title', 'status', 'openedAt', 'closedAt', 'note'],
  },
  {
    key: 'relatives',
    section: 'hr',
    title: 'Сотрудники и их родственники',
    model: 'employeeRelative',
    orderBy: { createdAt: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
    },
    fields: [
      'employeeId',
      'fullName',
      'relation',
      'birthDate',
      'phone',
      'gender',
      'workplace',
      'dependent',
      'isHidden',
    ],
  },
  {
    key: 'access-grants',
    section: 'hr',
    title: 'Доступы сотрудников',
    model: 'employeeAccessGrant',
    orderBy: { grantedAt: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
    },
    fields: ['employeeId', 'accessType', 'resource', 'grantedAt', 'expiresAt', 'isActive', 'note'],
    activeField: 'isActive',
  },
  {
    key: 'time-types',
    section: 'attendance',
    title: 'Виды рабочего времени',
    model: 'timeType',
    orderBy: { name: 'asc' },
    include: {
      parent: { select: { id: true, name: true, code: true } },
    },
    fields: [
      'code',
      'name',
      'letterCode',
      'digitalCode',
      'planLoad',
      'color',
      'parentId',
      'isPaid',
      'isActive',
      'sortOrder',
    ],
    activeField: 'isActive',
  },
  {
    key: 'report-templates',
    section: 'reports',
    title: 'Шаблоны отчётов',
    model: 'reportTemplate',
    orderBy: { createdAt: 'desc' },
    fields: [
      'code',
      'name',
      'kind',
      'source',
      'sourceType',
      'fileName',
      'fileUrl',
      'templateGroup',
      'templateType',
      'sortOrder',
      'useNameInReport',
      'createdBy',
      'definition',
      'isActive',
    ],
    activeField: 'isActive',
  },
  {
    key: 'dynamic-fields',
    section: 'settings',
    title: 'Динамические поля',
    model: 'dynamicField',
    orderBy: { name: 'asc' },
    fields: [
      'code',
      'name',
      'dataType',
      'referenceSource',
      'objectCode',
      'options',
      'isActive',
    ],
    activeField: 'isActive',
  },
  {
    key: 'dynamic-objects',
    section: 'settings',
    title: 'Объекты',
    model: 'dynamicObject',
    orderBy: { sortOrder: 'asc' },
    fields: ['code', 'name', 'kind', 'sortOrder', 'isActive'],
    activeField: 'isActive',
  },
  {
    key: 'accrual-types',
    section: 'payroll',
    title: 'Начисления',
    model: 'accrualType',
    orderBy: { sortOrder: 'asc' },
    fields: [
      'code',
      'name',
      'shortName',
      'description',
      'sortOrder',
      'isActive',
      'purpose',
      'periodCalc',
      'resultMode',
      'formula',
      'taxNdfl',
      'taxInps',
      'taxOss',
      'accountingMode',
    ],
    activeField: 'isActive',
  },
  {
    key: 'deduction-types',
    section: 'payroll',
    title: 'Удержания',
    model: 'deductionType',
    orderBy: { sortOrder: 'asc' },
    fields: [
      'code',
      'name',
      'shortName',
      'description',
      'sortOrder',
      'isActive',
      'purpose',
      'periodCalc',
      'resultMode',
      'formula',
      'accountingMode',
      'account',
    ],
    activeField: 'isActive',
  },
  {
    key: 'fact-types',
    section: 'payroll',
    title: 'Типы фактов',
    model: 'factType',
    orderBy: { name: 'asc' },
    include: {
      parent: { select: { id: true, name: true, code: true } },
    },
    fields: [
      'code',
      'name',
      'unit',
      'parentId',
      'accrualName',
      'registry',
      'isActive',
      'sortOrder',
    ],
    activeField: 'isActive',
  },
  {
    key: 'facts',
    section: 'payroll',
    title: 'Факты',
    model: 'fact',
    orderBy: { factDate: 'desc' },
    include: {
      employee: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          middleName: true,
          tabNumber: true,
        },
      },
      division: { select: { id: true, code: true, name: true } },
      factType: { select: { id: true, code: true, name: true } },
    },
    fields: [
      'employeeId',
      'divisionId',
      'factTypeId',
      'value',
      'factDate',
      'employmentSource',
      'status',
    ],
  },
  {
    key: 'payroll-lines',
    section: 'payroll',
    title: 'Все начисления',
    model: 'payrollLine',
    orderBy: { createdAt: 'desc' },
    include: {
      employee: { select: { id: true, firstName: true, lastName: true, tabNumber: true } },
      period: true,
    },
    fields: ['periodId', 'employeeId', 'type', 'status', 'description', 'amount', 'workDays', 'lateMinutes', 'absenceDays', 'postedAt'],
  },
];

export function findResource(key: string): CatalogResource | undefined {
  return CATALOG_RESOURCES.find((r) => r.key === key);
}
