/** Verifix-aligned navigation: existing app routes + catalog resources + reports. */

import { REPORTS_NAV_FLAT } from './reports-nav';

export type NavLink = {
  href: string;
  label: string;
  /** optional badge */
  badge?: string;
};

export type NavGroup = {
  label: string;
  items: NavLink[];
};

export const CATALOG_NAV: NavGroup[] = [
  {
    label: 'Главная',
    items: [
      { href: '/dashboard', label: 'Статистика посещений' },
      { href: '/catalog', label: 'Каталог (все модули)' },
      { href: '/employees', label: 'Сотрудники' },
      { href: '/employees?tab=dismissed', label: 'Уволенные сотрудники' },
      { href: '/employees?tab=gph', label: 'Сотрудники по договору ГПХ' },
      { href: '/divisions', label: 'Организационная структура' },
      { href: '/catalog/persons', label: 'Физические лица' },
    ],
  },
  {
    label: 'Кадры',
    items: [
      { href: '/catalog/hr-documents', label: 'Все кадровые документы' },
      { href: '/catalog/transfers', label: 'Кадровые переводы' },
      { href: '/catalog/name-changes', label: 'Реестр изменения имени сотрудника' },
      { href: '/catalog/wage-changes', label: 'Все изменения в оплате труда' },
      { href: '/catalog/clearance-sheets', label: 'Обходные листы' },
      { href: '/catalog/clearance-templates', label: 'Шаблоны обходных листов' },
      { href: '/catalog/absences', label: 'Все отсутствия сотрудников' },
      { href: '/catalog/absence-types', label: 'Типы отпуска' },
      { href: '/catalog/timesheet-adjustments', label: 'Корректировки табеля' },
      { href: '/catalog/hr-requests', label: 'Заявки на кадровые изменения' },
      { href: '/catalog/incidents', label: 'Инциденты' },
      { href: '/catalog/incident-types', label: 'Типы инцидента' },
      { href: '/catalog/gph-contracts', label: 'Договор ГПХ' },
      { href: '/divisions?tab=divisions', label: 'Подразделения' },
      { href: '/catalog/division-groups', label: 'Группы отделов' },
      { href: '/positions?tab=positions', label: 'Должности' },
      { href: '/positions?tab=groups', label: 'Группа должностей' },
      { href: '/catalog/position-groups', label: 'Группа должностей (справочник)' },
      { href: '/catalog/grades', label: 'Разряды' },
      { href: '/catalog/staff-positions', label: 'Позиции' },
      { href: '/catalog/staff-positions/structure', label: 'Оргструктура по позициям' },
      { href: '/catalog/tariff-groups', label: 'Тарифные группы' },
      { href: '/catalog/tariff-approvals', label: 'Утверждения тарифных групп' },
      { href: '/catalog/grade-history', label: 'Повышение разрядов' },
      { href: '/catalog/career-paths', label: 'Карьерный путь' },
      { href: '/catalog/career-steps', label: 'Карьерный путь — шаги' },
      { href: '/catalog/personnel-changes', label: 'Кадровые изменения' },
      { href: '/catalog/division-stats', label: 'Статистика работы подразделений' },
      { href: '/catalog/year-summary', label: 'Итоги года' },
      { href: '/catalog/dismissal-analytics', label: 'Причины увольнений' },
      { href: '/catalog/personnel-changes', label: 'Кадровые изменения' },
      { href: '/catalog/dismissal-reasons', label: 'Причины увольнения' },
      { href: '/catalog/relatives', label: 'Родственники' },
      { href: '/catalog/candidates', label: 'Кандидаты' },
      { href: '/catalog/vacancies', label: 'Вакансии' },
      { href: '/catalog/access-grants', label: 'Доступы сотрудников' },
    ],
  },
  {
    label: 'Посещения',
    items: [
      { href: '/catalog/work-schedules', label: 'Графики работы' },
      { href: '/catalog/absence-requests', label: 'Запросы на отсутствие' },
      { href: '/catalog/schedule-change-requests', label: 'Запросы на изменение графика' },
      { href: '/catalog/internal-trips', label: 'Внутренние командировки' },
      { href: '/catalog/location-requests', label: 'Запросы на локацию' },
      { href: '/catalog/overtime-requests', label: 'Запросы на сверхурочные' },
      { href: '/catalog/locations', label: 'Локации' },
      { href: '/catalog/devices', label: 'Устройства' },
      { href: '/attendance/marks', label: 'Отметки' },
      { href: '/catalog/schedule-overrides', label: 'Индивидуальные графики' },
      {
        href: '/catalog/position-schedules',
        label: 'Индивидуальные графики для позиций',
      },
      { href: '/catalog/rosters', label: 'Расписания' },
      {
        href: '/catalog/roster-change-requests',
        label: 'Запросы на изменение расписания',
      },
      { href: '/catalog/schedule-shifts', label: 'Список смен расписания' },
    ],
  },
  {
    label: 'Зарплата',
    items: [
      { href: '/payroll/fine-policies', label: 'Политики штрафов' },
      { href: '/payroll/allowance-policies', label: 'Политики выплат' },
      { href: '/payroll/timesheets', label: 'Табель' },
      { href: '/payroll/accruals', label: 'Все начисления' },
      { href: '/catalog/settlements', label: 'Взаиморасчеты' },
      { href: '/payroll/vedomost', label: 'Ведомость' },
      { href: '/payroll/manual', label: 'Ручные операции' },
      { href: '/catalog/gph-services', label: 'Список услуг договора ГПХ' },
      { href: '/catalog/sales-accruals', label: 'Начисления процентов от продаж' },
      { href: '/catalog/one-time-accruals', label: 'Разовые начисления' },
      { href: '/catalog/loans', label: 'Займы' },
      { href: '/catalog/payment-orders', label: 'Поручения' },
      { href: '/catalog/travel-expenses', label: 'Авансовый отчет по командировке' },
      { href: '/catalog/bonus-accruals', label: 'Бонусные начисления' },
    ],
  },
  {
    label: 'Отчетность',
    items: REPORTS_NAV_FLAT,
  },
  {
    label: 'Настройки',
    items: [
      { href: '/settings?tab=main', label: 'Главное' },
      { href: '/settings?tab=org', label: 'Организация' },
      { href: '/settings?tab=dictionaries', label: 'Справочники' },
      { href: '/settings?tab=extra', label: 'Дополнительные справочники' },
      { href: '/catalog/employment-sources', label: 'Источники занятости' },
      { href: '/catalog/indicators', label: 'Показатели' },
      { href: '/catalog/avg-salaries', label: 'Средние зарплаты' },
      { href: '/catalog/coa', label: 'План счетов' },
      { href: '/catalog/cashboxes', label: 'Кассы' },
      { href: '/catalog/currencies', label: 'Валюты' },
      { href: '/catalog/nationality', label: 'Национальность' },
      { href: '/settings?tab=admin', label: 'Администрирование' },
      { href: '/settings/organizations', label: 'Организации' },
      { href: '/settings/users', label: 'Пользователи и роли' },
      { href: '/settings/users/roles', label: 'Роли' },
      { href: '/settings/countries', label: 'Регионы / Страны' },
      { href: '/settings/countries/history', label: 'История изменений (регионы)' },
      { href: '/settings/banks', label: 'Банки' },
      { href: '/settings/banks/import', label: 'Банки (импорт)' },
      { href: '/settings/quickstart', label: 'Инструкция для быстрого запуска' },
      { href: '/settings/photos', label: 'Загрузка фотографий сотрудников' },
      { href: '/settings/person-docs', label: 'Импорт персональных документов' },
      { href: '/settings?tab=integrations', label: 'Внешние системы' },
      { href: '/settings/artix', label: 'Настройки ARTIX' },
      { href: '/settings/iiko', label: 'Настройки IIKO' },
      { href: '/settings/iiko-sales', label: 'Продажи IIKO' },
      { href: '/settings/billz', label: 'Настройки Billz 2.0' },
      { href: '/settings/billz-sales', label: 'Продажи Billz 1.0' },
      { href: '/settings?tab=audit', label: 'Аудит' },
      { href: '/tenants', label: 'Tenants', badge: 'platform' },
    ],
  },
];

/** Field labels for generic catalog forms */
/** Field labels for generic catalog forms — Russian Verifix 1:1 */
export type FieldDef = {
  name: string;
  label: string;
  type?: string;
  required?: boolean;
};

export const RESOURCE_META: Record<string, { title: string; fields: FieldDef[] }> = {
  'division-groups': {
    title: 'Группы отделов',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
    ],
  },
  'position-groups': {
    title: 'Группа должностей',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
    ],
  },
  grades: {
    title: 'Разряды',
    fields: [
      { name: 'code', label: 'Код' },
      { name: 'name', label: 'Название', required: true },
      { name: 'level', label: 'Порядковый номер', type: 'number' },
      { name: 'isActive', label: 'Статус', type: 'boolean' },
    ],
  },
  'grade-history': {
    title: 'Повышение разрядов',
    fields: [
      { name: 'documentDate', label: 'Дата', type: 'date', required: true },
      { name: 'documentNumber', label: 'Номер' },
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'note', label: 'Примечание' },
      { name: 'status', label: 'Состояние' },
    ],
  },
  'career-paths': {
    title: 'Карьерный путь',
    fields: [
      { name: 'name', label: 'Название', required: true },
      { name: 'code', label: 'Код' },
      { name: 'sortOrder', label: 'Порядковый номер', type: 'number' },
      { name: 'isActive', label: 'Статус', type: 'boolean' },
    ],
  },
  'tariff-groups': {
    title: 'Тарифные группы',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
      { name: 'gradeId', label: 'Разряд' },
      { name: 'baseRate', label: 'Ставка', type: 'number', required: true },
    ],
  },
  'tariff-approvals': {
    title: 'Утверждения тарифных групп',
    fields: [
      { name: 'tariffGroupId', label: 'Тарифная группа', required: true },
      { name: 'status', label: 'Статус (pending/approved/rejected)' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'staff-positions': {
    title: 'Позиции',
    fields: [
      { name: 'divisionId', label: 'Подразделение', required: true },
      { name: 'openedAt', label: 'Дата открытия', type: 'date', required: true },
      { name: 'closedAt', label: 'Дата закрытия', type: 'date' },
      { name: 'positionId', label: 'Должность', required: true },
      { name: 'groupName', label: 'Группа позиций' },
      { name: 'gradeId', label: 'Разряд' },
      { name: 'scheduleId', label: 'График работы' },
      { name: 'vacationDays', label: 'Кол-во отпускных дней', type: 'number' },
      { name: 'roles', label: 'Роли' },
      { name: 'code', label: 'Код' },
      { name: 'headcount', label: 'Количество единиц', type: 'number', required: true },
      { name: 'title', label: 'Название', required: true },
      { name: 'isActive', label: 'Статус', type: 'boolean' },
      { name: 'isPrimary', label: 'Основной', type: 'boolean' },
      { name: 'contractualSalary', label: 'Договорная зарплата', type: 'boolean' },
    ],
  },
  'dismissal-reasons': {
    title: 'Причины увольнения',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
      { name: 'groupName', label: 'Группа причин увольнения' },
      { name: 'basisType', label: 'Тип основания (positive/negative)' },
    ],
  },
  'clearance-templates': {
    title: 'Шаблоны обходных листов',
    fields: [
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'positionId', label: 'Должность' },
      { name: 'requireManagerSign', label: 'Руководитель', type: 'checkbox' },
      {
        name: 'requireHigherManagerSign',
        label: 'Вышестоящий руководитель',
        type: 'checkbox',
      },
    ],
  },
  'clearance-sheets': {
    title: 'Обходные листы',
    fields: [
      { name: 'number', label: 'Номер' },
      { name: 'documentDate', label: 'Дата', type: 'date' },
      { name: 'employeeId', label: 'Владелец', required: true },
      { name: 'templateId', label: 'Шаблон' },
      { name: 'title', label: 'Наименование', required: true },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'incident-types': {
    title: 'Типы инцидента',
    fields: [
      { name: 'name', label: 'Название', required: true },
      { name: 'accrualName', label: 'Начисление', required: true },
    ],
  },
  incidents: {
    title: 'Инциденты',
    fields: [
      { name: 'occurredAt', label: 'Дата инцидента', type: 'date', required: true },
      { name: 'number', label: 'Номер инцидента' },
      { name: 'incidentTypeId', label: 'Тип инцидента', required: true },
      { name: 'employeeId', label: 'Физическое лицо', required: true },
      { name: 'managerId', label: 'Руководитель' },
      { name: 'action', label: 'Действие' },
      { name: 'damageAmount', label: 'Сумма ущерба' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'gph-contracts': {
    title: 'Договор ГПХ',
    fields: [
      { name: 'employeeId', label: 'Сотрудник (ГПХ)', required: true },
      { name: 'personId', label: 'Физическое лицо' },
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'number', label: 'Номер договора', required: true },
      { name: 'title', label: 'Наименование', required: true },
      { name: 'startDate', label: 'Дата начала', type: 'date', required: true },
      { name: 'endDate', label: 'Дата окончания', type: 'date' },
      { name: 'amount', label: 'Сумма', type: 'number' },
      { name: 'allowAddService', label: 'Доступ на добавление услуги (true/false)' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'gph-services': {
    title: 'Список услуг договора ГПХ',
    fields: [
      { name: 'contractId', label: 'Договор' },
      { name: 'month', label: 'Месяц', type: 'date' },
      { name: 'name', label: 'Наименование' },
      { name: 'code', label: 'Код' },
      { name: 'status', label: 'Состояние (draft/posted/cancelled)' },
      { name: 'unitPrice', label: 'Цена', type: 'number' },
      { name: 'unit', label: 'Единица' },
    ],
  },
  'name-changes': {
    title: 'Реестр изменения имени сотрудника',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'newLastName', label: 'Новая фамилия', required: true },
      { name: 'newFirstName', label: 'Новое имя', required: true },
      { name: 'newMiddleName', label: 'Новое отчество' },
      { name: 'effectiveAt', label: 'Дата', type: 'date', required: true },
      { name: 'documentNumber', label: 'Номер документа' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'wage-changes': {
    title: 'Изменения в оплате труда',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'newAmount', label: 'Новая сумма', type: 'number', required: true },
      { name: 'effectiveAt', label: 'Дата', type: 'date', required: true },
      { name: 'reason', label: 'Причина' },
      { name: 'documentNumber', label: 'Номер документа' },
    ],
  },
  'location-types': {
    title: 'Типы локаций',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
    ],
  },
  'timesheet-adjustments': {
    title: 'Корректировки табеля',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'workDate', label: 'Дата', type: 'date', required: true },
      { name: 'newStatus', label: 'Новый статус (on_time/late/absent/leave/day_off)', required: true },
      { name: 'reason', label: 'Причина', required: true },
    ],
  },
  'schedule-shifts': {
    title: 'Смены расписания',
    fields: [
      { name: 'scheduleId', label: 'График', required: true },
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
      { name: 'startTime', label: 'Начало (HH:MM)', required: true },
      { name: 'endTime', label: 'Окончание (HH:MM)', required: true },
      { name: 'weekday', label: 'День недели (0-6)', type: 'number' },
    ],
  },
  'schedule-overrides': {
    title: 'Индивидуальные графики',
    fields: [
      { name: 'documentDate', label: 'Дата', type: 'date', required: true },
      { name: 'number', label: 'Номер' },
      { name: 'month', label: 'Месяц', type: 'date', required: true },
      { name: 'kind', label: 'Тип графика' },
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'rosters': {
    title: 'Расписание',
    fields: [
      { name: 'name', label: 'Название', required: true },
      { name: 'documentDate', label: 'Дата', type: 'date', required: true },
      { name: 'number', label: 'Номер' },
      { name: 'month', label: 'Месяц', type: 'date', required: true },
      { name: 'scheduleId', label: 'График работы', required: true },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'position-schedules': {
    title: 'Индивидуальные графики для позиций',
    fields: [
      { name: 'documentDate', label: 'Дата', type: 'date', required: true },
      { name: 'number', label: 'Номер' },
      { name: 'month', label: 'Месяц', type: 'date', required: true },
      { name: 'kind', label: 'Тип графика' },
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'internal-trips': {
    title: 'Внутренняя командировка',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'locationId', label: 'Локация' },
      { name: 'title', label: 'Наименование', required: true },
      { name: 'startDate', label: 'Начало', type: 'date', required: true },
      { name: 'endDate', label: 'Окончание', type: 'date', required: true },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'gps-tracks': {
    title: 'GPS трек',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'latitude', label: 'Широта', type: 'number', required: true },
      { name: 'longitude', label: 'Долгота', type: 'number', required: true },
      { name: 'recordedAt', label: 'Время', type: 'datetime-local', required: true },
      { name: 'accuracyM', label: 'Точность (м)', type: 'number' },
    ],
  },
  'payment-orders': {
    title: 'Поручения',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'accrualName', label: 'Начисление' },
      { name: 'amount', label: 'Сумма поручения', type: 'number', required: true },
      { name: 'startDate', label: 'Дата начала', type: 'date', required: true },
      { name: 'endDate', label: 'Дата окончания', type: 'date' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'account-pairs': {
    title: 'Парные счета',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
      { name: 'debitAccount', label: 'Дебет', required: true },
      { name: 'creditAccount', label: 'Кредит', required: true },
    ],
  },
  settlements: {
    title: 'Взаиморасчеты',
    fields: [
      { name: 'title', label: 'Наименование', required: true },
      { name: 'amount', label: 'Сумма', type: 'number', required: true },
      { name: 'employeeId', label: 'Сотрудник' },
      { name: 'accountPairId', label: 'Парный счёт' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'sales-policies': {
    title: 'Настройка процентов продаж',
    fields: [
      { name: 'positionId', label: 'Должность' },
      { name: 'personalPercent', label: 'Личные продажи', type: 'number' },
      { name: 'divisionPercent', label: 'Продажи подразделения', type: 'number' },
    ],
  },
  'sales-accruals': {
    title: 'Начисления процентов от продаж',
    fields: [
      { name: 'number', label: 'Номер' },
      { name: 'docDate', label: 'Дата', type: 'date', required: true },
      { name: 'periodFrom', label: 'Дата начала', type: 'date', required: true },
      { name: 'periodTo', label: 'Дата окончания', type: 'date', required: true },
      { name: 'title', label: 'Название' },
      { name: 'paymentType', label: 'Тип оплаты (cash/bank)' },
      { name: 'salesKind', label: 'Тип продаж (personal/division)' },
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'positionId', label: 'Должность' },
      { name: 'cashbox', label: 'Касса' },
      { name: 'bankAccount', label: 'Расчетный счет' },
      { name: 'rounding', label: 'Округление' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'one-time-accruals': {
    title: 'Разовые начисления',
    fields: [
      { name: 'kind', label: 'Тип (accrual/deduction)' },
      { name: 'number', label: 'Номер' },
      { name: 'docDate', label: 'Дата', type: 'date', required: true },
      { name: 'month', label: 'Месяц', type: 'date', required: true },
      { name: 'title', label: 'Название документа' },
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'currency', label: 'Валюта' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  loans: {
    title: 'Займы',
    fields: [
      { name: 'number', label: 'Номер займа' },
      { name: 'loanDate', label: 'Дата займа', type: 'date', required: true },
      { name: 'contractNumber', label: 'Номер договора' },
      { name: 'contractDate', label: 'Дата договора', type: 'date' },
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'startDate', label: 'С', type: 'date', required: true },
      { name: 'endDate', label: 'До', type: 'date' },
      { name: 'principal', label: 'Сумма', type: 'number', required: true },
      { name: 'currency', label: 'Валюта' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'travel-expenses': {
    title: 'Авансовый отчет по командировке',
    fields: [
      { name: 'number', label: 'Номер' },
      { name: 'docDate', label: 'Дата', type: 'date', required: true },
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'tripId', label: 'Командировка', required: true },
      { name: 'currency', label: 'Валюта' },
      { name: 'advance', label: 'Аванс', type: 'number' },
      { name: 'amount', label: 'Расходы', type: 'number' },
      { name: 'calcForSalary', label: 'Рассчитать для зарплаты', type: 'checkbox' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'bonus-accruals': {
    title: 'Бонусные начисления',
    fields: [
      { name: 'kind', label: 'Тип (fact/kpi)' },
      { name: 'number', label: 'Номер' },
      { name: 'docDate', label: 'Дата', type: 'date', required: true },
      { name: 'startDate', label: 'Дата начала', type: 'date', required: true },
      { name: 'endDate', label: 'Дата окончания', type: 'date', required: true },
      { name: 'divisionId', label: 'Подразделение' },
      { name: 'factTypeId', label: 'Тип факта' },
      { name: 'considerPayroll', label: 'Учет оплаты труда', type: 'checkbox' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  candidates: {
    title: 'Кандидаты',
    fields: [
      { name: 'fullName', label: 'ФИО', required: true },
      { name: 'staffPositionId', label: 'Позиция' },
      { name: 'positionName', label: 'Должность' },
      { name: 'phone', label: 'Телефон' },
      { name: 'email', label: 'Email' },
      { name: 'introducedAt', label: 'Дата введения', type: 'date' },
      { name: 'birthDate', label: 'Дата рождения', type: 'date' },
      { name: 'gender', label: 'Пол' },
      { name: 'personType', label: 'Тип физического лица' },
      { name: 'employmentSource', label: 'Источник занятости' },
      { name: 'category', label: 'Категория' },
      { name: 'education', label: 'Образование' },
      { name: 'languages', label: 'Знание языков' },
      { name: 'status', label: 'Статус' },
      { name: 'note', label: 'Примечание' },
    ],
  },
  vacancies: {
    title: 'Вакансии',
    fields: [
      { name: 'staffPositionId', label: 'Позиция', required: true },
      { name: 'title', label: 'Наименование', required: true },
      { name: 'note', label: 'Примечание' },
    ],
  },
  relatives: {
    title: 'Родственники',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'fullName', label: 'ФИО', required: true },
      { name: 'relation', label: 'Степень родства', required: true },
      { name: 'birthDate', label: 'Дата рождения', type: 'date' },
      { name: 'phone', label: 'Телефон' },
    ],
  },
  'access-grants': {
    title: 'Доступы',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'accessType', label: 'Тип доступа', required: true },
      { name: 'resource', label: 'Ресурс', required: true },
      { name: 'note', label: 'Примечание' },
    ],
  },
  'time-types': {
    title: 'Виды времени',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
    ],
  },
  'report-templates': {
    title: 'Шаблоны отчётов',
    fields: [
      { name: 'code', label: 'Код', required: true },
      { name: 'name', label: 'Наименование', required: true },
      { name: 'kind', label: 'Вид', required: true },
    ],
  },
  persons: {
    title: 'Физические лица',
    fields: [
      { name: 'lastName', label: 'Фамилия', required: true },
      { name: 'firstName', label: 'Имя', required: true },
      { name: 'middleName', label: 'Отчество' },
      { name: 'birthDate', label: 'Дата рождения', type: 'date' },
      { name: 'gender', label: 'Пол' },
      { name: 'phone', label: 'Телефон' },
      { name: 'email', label: 'Email' },
      { name: 'pinfl', label: 'ПИНФЛ' },
    ],
  },
  'hr-documents': {
    title: 'Все кадровые документы',
    fields: [
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'type', label: 'Тип (hire/transfer/dismiss/name_change/wage_change/other)', required: true },
      { name: 'title', label: 'Заголовок', required: true },
      { name: 'documentDate', label: 'Дата', type: 'date', required: true },
      { name: 'number', label: 'Номер' },
      { name: 'note', label: 'Примечание' },
      { name: 'divisionId', label: 'Подразделение (hire/transfer)' },
      { name: 'positionId', label: 'Должность (hire/transfer)' },
      { name: 'baseSalary', label: 'Оклад (hire)', type: 'number' },
      { name: 'dismissalReasonId', label: 'Причина увольнения (dismiss)' },
      { name: 'newLastName', label: 'Новая фамилия (name_change)' },
      { name: 'newFirstName', label: 'Новое имя (name_change)' },
      { name: 'newMiddleName', label: 'Новое отчество (name_change)' },
      { name: 'newAmount', label: 'Новый оклад (wage_change)', type: 'number' },
    ],
  },
  'absence-types': {
    title: 'Типы отпуска',
    fields: [
      { name: 'name', label: 'Название', required: true },
      { name: 'code', label: 'Код' },
      { name: 'calcKind', label: 'Вид начисления (annual/one_time)' },
      { name: 'timeTypeId', label: 'Вид рабочего времени' },
      { name: 'accrualName', label: 'Начисления' },
      { name: 'description', label: 'Описание' },
      { name: 'isActive', label: 'Активный (true/false)' },
    ],
  },
  'career-steps': {
    title: 'Карьерный путь — шаги',
    fields: [
      { name: 'careerPathId', label: 'Карьерный путь', required: true },
      { name: 'title', label: 'Наименование', required: true },
      { name: 'positionId', label: 'Должность' },
      { name: 'gradeId', label: 'Разряд' },
      { name: 'sortOrder', label: 'Порядок', type: 'number' },
      { name: 'minMonths', label: 'Мин. месяцев', type: 'number' },
    ],
  },
  'payroll-lines': {
    title: 'Все начисления',
    fields: [
      { name: 'periodId', label: 'Период', required: true },
      { name: 'employeeId', label: 'Сотрудник', required: true },
      { name: 'type', label: 'Тип (base/bonus/penalty/deduction/one_time/other)', required: true },
      { name: 'amount', label: 'Сумма', type: 'number', required: true },
      { name: 'description', label: 'Примечание' },
    ],
  },
  'loan-payments': {
    title: 'Займы — платежи',
    fields: [
      { name: 'loanId', label: 'Займ', required: true },
      { name: 'amount', label: 'Сумма', type: 'number', required: true },
      { name: 'paidAt', label: 'Дата', type: 'datetime-local' },
      { name: 'note', label: 'Примечание' },
    ],
  },
};

export const REPORT_KINDS: Record<string, { title: string; path: string }> = {
  'division-stats': { title: 'Статистика работы подразделений', path: '/api/catalog/analytics/division-stats' },
  'year-summary': { title: 'Итоги года', path: '/api/catalog/analytics/year-summary' },
  staffing: { title: 'Отчет по штатному расписанию', path: '/api/catalog/analytics/staffing' },
  gender: { title: 'Отчет по гендерному разделению сотрудников', path: '/api/catalog/analytics/gender' },
  'movement-divisions': {
    title: 'Отчет по движению сотрудников (подразделения)',
    path: '/api/catalog/analytics/movement-divisions',
  },
  'movement-staff': {
    title: 'Отчет по движению сотрудников (штаты)',
    path: '/api/catalog/analytics/movement-staff',
  },
  'dismissals-by-reason': { title: 'Отчет по причинам увольнения', path: '/api/catalog/analytics/dismissals-by-reason' },
  'dismissal-dashboard': { title: 'Причины увольнений', path: '/api/catalog/analytics/dismissal-dashboard' },
  'dismissals-by-division': { title: 'Отчет увольнений по подразделениям', path: '/api/catalog/analytics/dismissals-by-division' },
  grades: { title: 'Отчет по разрядам', path: '/api/catalog/analytics/grades' },
  'grade-changes': { title: 'Отчет по изменению разрядов', path: '/api/catalog/analytics/grade-changes' },
  vacancies: { title: 'Отчет по вакантным позициям', path: '/api/catalog/analytics/vacancies' },
  candidates: { title: 'Отчет по кандидатам', path: '/api/catalog/analytics/candidates' },
  tenure: { title: 'Отчет по стажам', path: '/api/catalog/analytics/tenure' },
  relatives: { title: 'Сотрудники и их родственники', path: '/api/catalog/analytics/relatives' },
  access: { title: 'Отчет по доступам сотрудников', path: '/api/catalog/analytics/access' },
  distance: { title: 'Отчет по пройденному расстоянию', path: '/api/catalog/analytics/distance' },
  shifts: { title: 'Отчет посещений сотрудников по сменам', path: '/api/catalog/analytics/shifts' },
  'time-types': { title: 'Отчет по видам времени', path: '/api/catalog/analytics/time-types' },
  lateness: { title: 'Отчет по опозданиям', path: '/api/catalog/analytics/lateness' },
  'schedule-plan': { title: 'Отчет по плану графиков', path: '/api/catalog/analytics/schedule-plan' },
  schedules: { title: 'Отчет по расписанию', path: '/api/catalog/analytics/schedules' },
  employees: { title: 'Отчет по сотрудникам', path: '/api/catalog/analytics/employees' },
  occupancy: { title: 'Отчет по занятости', path: '/api/catalog/analytics/occupancy' },
  penalties: { title: 'Отчет по штрафам', path: '/api/catalog/analytics/penalties' },
  'one-time': { title: 'Отчет по разовым начислениям', path: '/api/catalog/analytics/one-time' },
  'division-expenses': { title: 'Расходы по подразделениям', path: '/api/catalog/analytics/division-expenses' },
  fot: { title: 'ФОТ отчет', path: '/api/catalog/analytics/fot' },
  'payroll-book': { title: 'Книга начисления заработной платы', path: '/api/catalog/analytics/payroll-book' },
  'account-balance': {
    title: 'Оборотно-сальдовая ведомость по счету',
    path: '/api/catalog/analytics/account-balance',
  },
  'trial-balance': {
    title: 'Оборотно-сальдовая ведомость',
    path: '/api/catalog/analytics/trial-balance',
  },
  'payroll-grouped': {
    title: 'Итоговый отчет по начислениям с группировками',
    path: '/api/catalog/analytics/payroll-grouped',
  },
  'preliminary-salary': { title: 'Отчет по предварительному окладу', path: '/api/catalog/analytics/preliminary-salary' },
  payments: { title: 'Отчет по оплатам', path: '/api/catalog/analytics/payments' },
  hourly: { title: 'Почасовой отчет по посещениям', path: '/api/catalog/analytics/hourly' },
  'division-mode': { title: 'Отчет по режиму работы подразделения (период)', path: '/api/catalog/analytics/division-mode' },
  discipline: { title: 'Отчет по дисциплине посещений', path: '/api/catalog/analytics/discipline' },
  'timesheet-adjustments': { title: 'Отчет по корректировке табеля', path: '/api/catalog/analytics/timesheet-adjustments' },
  'positions-structure': { title: 'Оргструктура по позициям', path: '/api/catalog/analytics/positions-structure' },
  positions: { title: 'Отчет по позициям', path: '/api/catalog/analytics/positions' },
  'attendance-overview': { title: 'Отчет по посещениям сотрудников', path: '/api/catalog/analytics/attendance-overview' },
  'attendance-t13': { title: 'Отчет по посещениям сотрудников (Т-13)', path: '/api/catalog/analytics/attendance-overview' },
  'marks-detail': { title: 'Детальный отчет по отметкам', path: '/api/catalog/analytics/marks-detail' },
  'multi-shift': { title: 'Отчет посещений по многосменным графикам', path: '/api/catalog/analytics/multi-shift' },
};
