/**
 * Grid columns 1:1 with Verifix `:table` request `column` arrays,
 * mapped onto HR HUB Prisma field paths (flattenRow keys).
 * Order + Russian labels must match the captured screens.
 */

export type ColumnDef = {
  /** flattenRow / API field path */
  key: string;
  /** Russian header (Verifix UI) */
  label: string;
};

/** Общие label map for common keys */
export const COLUMN_LABELS: Record<string, string> = {
  tabNumber: 'Таб. №',
  employee_number: 'Таб. №',
  photo_sha: 'Фото',
  gender: 'Пол',
  name: 'ФИО',
  fullName: 'ФИО',
  firstName: 'Имя',
  lastName: 'Фамилия',
  middleName: 'Отчество',
  region_name: 'Регион',
  division_name: 'Подразделение',
  'division.name': 'Подразделение',
  job_name: 'Должность',
  'position.name': 'Должность',
  rank_name: 'Разряд',
  'grade.name': 'Разряд',
  status: 'Статус',
  status_name: 'Статус',
  isActive: 'Активен',
  code: 'Код',
  title: 'Наименование',
  number: 'Номер',
  documentDate: 'Дата',
  journal_date: 'Дата',
  journal_number: 'Номер',
  journal_type_name: 'Тип',
  employee_names: 'Сотрудники',
  'employee.lastName': 'Фамилия',
  'employee.firstName': 'Имя',
  'employee.tabNumber': 'Таб. №',
  posted: 'Проведён',
  posted_name: 'Проведение',
  postedAt: 'Дата проведения',
  type: 'Тип',
  amount: 'Сумма',
  note: 'Примечание',
  description: 'Описание',
  createdAt: 'Создан',
  effectiveAt: 'Дата изменения',
  startDate: 'Начало',
  endDate: 'Окончание',
  begin_date: 'Начало',
  end_date: 'Окончание',
  workDate: 'Дата',
  phone: 'Телефон',
  email: 'Email',
  pinfl: 'ПИНФЛ',
  birthDate: 'Дата рождения',
  level: 'Уровень',
  headcount: 'Штат',
  baseRate: 'Ставка',
  baseSalary: 'Оклад',
  principal: 'Сумма займа',
  remaining: 'Остаток',
  monthlyPayment: 'Ежемесячный платёж',
  severity: 'Критичность',
  occurredAt: 'Дата инцидента',
  relation: 'Степень родства',
  accessType: 'Тип доступа',
  resource: 'Ресурс',
  percent: 'Процент',
  salesAmount: 'Сумма продаж',
  commission: 'Комиссия',
  periodYear: 'Год',
  periodMonth: 'Месяц',
  debitAccount: 'Дебет',
  creditAccount: 'Кредит',
  unitPrice: 'Цена',
  unit: 'Ед.',
  address: 'Адрес',
  startTime: 'Начало',
  endTime: 'Окончание',
  weekday: 'День недели',
  latitude: 'Широта',
  longitude: 'Долгота',
  accuracyM: 'Точность (м)',
  recordedAt: 'Время',
  source: 'Источник',
  dueDate: 'Срок',
  settledAt: 'Дата закрытия',
  spentAt: 'Дата расхода',
  openedAt: 'Открыта',
  closedAt: 'Закрыта',
  grantedAt: 'Выдан',
  expiresAt: 'Истекает',
  kind: 'Вид',
  isPaid: 'Оплачиваемый',
  oldStatus: 'Старый статус',
  newStatus: 'Новый статус',
  reason: 'Причина',
  oldAmount: 'Старая сумма',
  newAmount: 'Новая сумма',
  oldLastName: 'Старая фамилия',
  oldFirstName: 'Старое имя',
  newLastName: 'Новая фамилия',
  newFirstName: 'Новое имя',
  newMiddleName: 'Новое отчество',
  documentNumber: 'Номер документа',
  completedAt: 'Завершён',
  workDays: 'Раб. дни',
  lateMinutes: 'Опоздание (мин)',
  absenceDays: 'Дни отсутствия',
  'period.year': 'Год',
  'period.month': 'Месяц',
  'incidentType.name': 'Тип инцидента',
  'template.name': 'Шаблон',
  'tariffGroup.name': 'Тарифная группа',
  'accountPair.name': 'Счёт',
  'policy.name': 'Политика',
  'staffPosition.title': 'Позиция',
  'location.name': 'Локация',
  'schedule.name': 'График',
  'contract.number': 'Договор',
  'trip.title': 'Командировка',
  employmentType: 'Тип занятости',
  hireDate: 'Дата приёма',
  dismissDate: 'Дата увольнения',
  faceIdStatus: 'Face ID',
};

export function labelFor(key: string): string {
  return COLUMN_LABELS[key] ?? key;
}

/**
 * Explicit column order per catalog resource (Verifix-aligned visible columns).
 * Keys are flattenRow paths present in API responses.
 */
export const RESOURCE_COLUMNS: Record<string, ColumnDef[]> = {
  persons: [
    { key: 'lastName', label: 'Фамилия' },
    { key: 'firstName', label: 'Имя' },
    { key: 'middleName', label: 'Отчество' },
    { key: 'gender', label: 'Пол' },
    { key: 'pinfl', label: 'ПИНФЛ' },
    { key: 'phone', label: 'Телефон' },
    { key: 'email', label: 'Email' },
    { key: 'isActive', label: 'Статус' },
  ],
  'hr-documents': [
    { key: 'documentDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'type', label: 'Тип' },
    { key: 'employee.lastName', label: 'Фамилия' },
    { key: 'employee.firstName', label: 'Имя' },
    { key: 'employee.tabNumber', label: 'Таб. №' },
    { key: 'title', label: 'Заголовок' },
    { key: 'status', label: 'Статус' },
    { key: 'postedAt', label: 'Проведён' },
  ],
  'name-changes': [
    { key: 'effectiveAt', label: 'Дата' },
    { key: 'documentNumber', label: 'Номер' },
    { key: 'employee.lastName', label: 'Сотрудники' },
    { key: 'employee.firstName', label: 'Имя' },
    { key: 'employee.tabNumber', label: 'Таб. №' },
    { key: 'oldLastName', label: 'Предыдущие имена' },
    { key: 'oldFirstName', label: 'Пред. имя' },
    { key: 'newLastName', label: 'Новая фамилия' },
    { key: 'status', label: 'Проведен' },
  ],
  'wage-changes': [
    { key: 'effectiveAt', label: 'Дата' },
    { key: 'documentNumber', label: 'Номер' },
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'employee.tabNumber', label: 'Таб. №' },
    { key: 'oldAmount', label: 'Старая сумма' },
    { key: 'newAmount', label: 'Новая сумма' },
    { key: 'reason', label: 'Причина' },
    { key: 'status', label: 'Статус' },
  ],
  'clearance-sheets': [
    { key: 'title', label: 'Номер / название' },
    { key: 'createdAt', label: 'Дата' },
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'employee.tabNumber', label: 'Таб. №' },
    { key: 'template.name', label: 'Шаблон' },
    { key: 'status', label: 'Статус' },
    { key: 'completedAt', label: 'Завершён' },
  ],
  'clearance-templates': [
    { key: 'code', label: 'Код' },
    { key: 'name', label: 'Наименование' },
    { key: 'isActive', label: 'Статус' },
  ],
  'timesheet-adjustments': [
    { key: 'documentDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'title', label: 'Название' },
    { key: 'division.name', label: 'Подразделение' },
    { key: 'periodFrom', label: 'Период с' },
    { key: 'periodTo', label: 'Период по' },
    { key: 'status', label: 'Проведен' },
  ],
  incidents: [
    { key: 'number', label: 'Номер инцидента' },
    { key: 'occurredAt', label: 'Дата инцидента' },
    { key: 'employee.lastName', label: 'Физическое лицо' },
    { key: 'incidentType.name', label: 'Тип инцидента' },
    { key: 'damageAmount', label: 'Сумма ущерба' },
    { key: 'action', label: 'Действие' },
  ],
  'incident-types': [
    { key: 'name', label: 'Название' },
    { key: 'accrualName', label: 'Начисление' },
    { key: 'isActive', label: 'Статус' },
  ],
  'gph-contracts': [
    { key: 'number', label: 'Номер договора' },
    { key: 'startDate', label: 'Дата начала' },
    { key: 'division.name', label: 'Подразделение' },
    { key: 'person.lastName', label: 'Физическое лицо' },
    { key: 'allowAddService', label: 'Доступ на добавление услуги' },
    { key: 'status', label: 'Проведен' },
    { key: 'title', label: 'Наименование' },
    { key: 'amount', label: 'Сумма' },
    { key: 'isActive', label: 'Активен' },
  ],
  'gph-services': [
    { key: 'contract.number', label: 'Номер договора' },
    { key: 'month', label: 'Месяц' },
    { key: 'contract.division.name', label: 'Подразделение' },
    { key: 'contract.person.lastName', label: 'Физическое лицо' },
    { key: 'status', label: 'Состояние' },
    { key: 'name', label: 'Наименование' },
    { key: 'code', label: 'Код' },
  ],
  'division-groups': [
    { key: 'code', label: 'Код' },
    { key: 'name', label: 'Наименование' },
    { key: 'isActive', label: 'Статус' },
  ],
  'position-templates': [
    { key: 'division', label: 'Подразделение' },
    { key: 'position', label: 'Должность' },
    { key: 'grade', label: 'Разряд' },
    { key: 'schedule', label: 'График работы' },
    { key: 'tariffGroup', label: 'Тарифная группа' },
  ],
  'position-groups': [
    { key: 'code', label: 'Код' },
    { key: 'name', label: 'Наименование' },
    { key: 'isActive', label: 'Статус' },
  ],
  grades: [
    { key: 'name', label: 'Наименование' },
    { key: 'code', label: 'Код' },
    { key: 'level', label: 'Уровень' },
    { key: 'isActive', label: 'Статус' },
  ],
  'grade-history': [
    { key: 'documentDate', label: 'Дата' },
    { key: 'documentNumber', label: 'Номер' },
    { key: 'division.name', label: 'Подразделение' },
    { key: 'status', label: 'Состояние' },
    { key: 'note', label: 'Примечание' },
  ],
  'career-paths': [
    { key: 'name', label: 'Название' },
    { key: 'code', label: 'Код' },
    { key: '_count.steps', label: 'Кол-во должностей' },
    { key: 'isActive', label: 'Статус' },
  ],
  'staff-positions': [
    { key: 'title', label: 'Наименование' },
    { key: 'code', label: 'Код' },
    { key: 'division.name', label: 'Подразделение' },
    { key: 'position.name', label: 'Должность' },
    { key: 'grade.name', label: 'Разряд' },
    { key: 'headcount', label: 'Штат' },
    { key: 'status', label: 'Статус' },
  ],
  'tariff-groups': [
    { key: 'name', label: 'Наименование' },
    { key: 'code', label: 'Код' },
    { key: 'grade.name', label: 'Разряд' },
    { key: 'baseRate', label: 'Ставка' },
    { key: 'isActive', label: 'Статус' },
  ],
  'tariff-approvals': [
    { key: 'createdAt', label: 'Дата' },
    { key: 'tariffGroup.name', label: 'Тарифная группа' },
    { key: 'status', label: 'Статус' },
    { key: 'note', label: 'Примечание' },
  ],
  'dismissal-reasons': [
    { key: 'code', label: 'Код' },
    { key: 'name', label: 'Наименование' },
    { key: 'groupName', label: 'Группа' },
    { key: 'basisType', label: 'Тип основания' },
    { key: 'isActive', label: 'Статус' },
  ],
  'career-steps': [
    { key: 'title', label: 'Наименование' },
    { key: 'sortOrder', label: 'Порядок' },
    { key: 'minMonths', label: 'Мин. мес.' },
    { key: 'positionId', label: 'Должность' },
    { key: 'gradeId', label: 'Разряд' },
  ],
  'absence-types': [
    { key: 'name', label: 'Название' },
    { key: 'timeType.name', label: 'Вид времени' },
    { key: 'isAnnual', label: 'Является ежегодным' },
    { key: 'requestTimeLimit', label: 'Ограничение времени запроса' },
    { key: 'allowEmployeeRequest', label: 'Разрешить сотрудникам создавать запрос' },
    { key: 'trackUnusedTime', label: 'Учитывать неиспользованное время' },
    { key: 'carryoverPolicy', label: 'Политика переноса' },
  ],
  'location-types': [
    { key: 'name', label: 'Наименование' },
    { key: 'code', label: 'Код' },
    { key: 'isActive', label: 'Статус' },
  ],
  'schedule-shifts': [
    { key: 'employee', label: 'Сотрудник' },
    { key: 'workDate', label: 'Дата' },
    { key: 'number', label: '№' },
    { key: 'shiftLabel', label: 'Смена' },
    { key: 'status', label: 'Статус' },
    { key: 'replaced', label: 'Заменено' },
    { key: 'source', label: 'Источник' },
    { key: 'schedule.name', label: 'График работы' },
  ],
  'schedule-overrides': [
    { key: 'documentDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'month', label: 'Месяц' },
    { key: 'kind', label: 'Тип графика' },
    { key: 'division.name', label: 'Подразделение' },
    { key: 'verified', label: 'Проверен' },
    { key: 'status', label: 'Статус' },
  ],
  'position-schedules': [
    { key: 'documentDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'month', label: 'Месяц' },
    { key: 'kind', label: 'Тип графика' },
    { key: 'division.name', label: 'Подразделение' },
    { key: 'verified', label: 'Проверен' },
    { key: 'status', label: 'Статус' },
  ],
  'internal-trips': [
    { key: 'createdAt', label: 'Создан' },
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'location.name', label: 'Локация' },
    { key: 'title', label: 'Наименование' },
    { key: 'startDate', label: 'Начало' },
    { key: 'endDate', label: 'Окончание' },
    { key: 'status', label: 'Статус' },
  ],
  'gps-tracks': [
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'latitude', label: 'Широта' },
    { key: 'longitude', label: 'Долгота' },
    { key: 'accuracyM', label: 'Точность (м)' },
    { key: 'recordedAt', label: 'Время' },
    { key: 'source', label: 'Источник' },
  ],
  'time-types': [
    { key: 'name', label: 'Название' },
    { key: 'parent.name', label: 'Родитель' },
    { key: 'letterCode', label: 'Буквенный код' },
    { key: 'digitalCode', label: 'Цифровой код' },
    { key: 'planLoad', label: 'Нагрузка на план' },
    { key: 'color', label: 'Цвет' },
  ],
  'payroll-lines': [
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'employee.tabNumber', label: 'Таб. №' },
    { key: 'type', label: 'Тип операции' },
    { key: 'amount', label: 'Сумма' },
    { key: 'status', label: 'Статус' },
    { key: 'period.year', label: 'Год' },
    { key: 'period.month', label: 'Месяц' },
    { key: 'description', label: 'Примечание' },
  ],
  'payment-orders': [
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'accrualName', label: 'Начисление' },
    { key: 'amount', label: 'Сумма поручения' },
    { key: 'startDate', label: 'Дата начала' },
    { key: 'endDate', label: 'Дата окончания' },
    { key: 'status', label: 'Состояние' },
  ],
  settlements: [
    { key: 'title', label: 'Наименование' },
    { key: 'createdAt', label: 'Дата' },
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'accountPair.name', label: 'Счёт' },
    { key: 'amount', label: 'Сумма' },
    { key: 'status', label: 'Статус' },
  ],
  'account-pairs': [
    { key: 'name', label: 'Наименование' },
    { key: 'code', label: 'Код' },
    { key: 'debitAccount', label: 'Дебет' },
    { key: 'creditAccount', label: 'Кредит' },
    { key: 'isActive', label: 'Статус' },
  ],
  'sales-policies': [
    { key: 'position.name', label: 'Должность' },
    { key: 'personalPercent', label: 'Личные продажи' },
    { key: 'divisionPercent', label: 'Продажи подразделения' },
  ],
  'sales-accruals': [
    { key: 'docDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'periodFrom', label: 'Дата начала' },
    { key: 'periodTo', label: 'Дата окончания' },
    { key: 'paymentType', label: 'Тип начисление' },
    { key: 'totalAmount', label: 'Сумма' },
    { key: 'status', label: 'Проведен' },
  ],
  'one-time-accruals': [
    { key: 'month', label: 'Месяц' },
    { key: 'docDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'currency', label: 'Валюта' },
    { key: 'title', label: 'Название документа' },
    { key: 'status', label: 'Проведен' },
  ],
  loans: [
    { key: 'number', label: 'Номер займа' },
    { key: 'loanDate', label: 'Дата займа' },
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'remaining', label: 'Оставшаяся сумма займа' },
    { key: 'principal', label: 'Сумма займа' },
    { key: 'startDate', label: 'От' },
    { key: 'endDate', label: 'До' },
    { key: 'status', label: 'Статус' },
  ],
  'loan-payments': [
    { key: 'paidAt', label: 'Дата' },
    { key: 'loanId', label: 'Займ' },
    { key: 'amount', label: 'Сумма' },
    { key: 'note', label: 'Примечание' },
  ],
  'travel-expenses': [
    { key: 'docDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'trip.title', label: 'Номер документа командировки' },
    { key: 'status', label: 'Состояние' },
  ],
  'bonus-accruals': [
    { key: 'docDate', label: 'Дата' },
    { key: 'number', label: 'Номер' },
    { key: 'startDate', label: 'Дата начала' },
    { key: 'endDate', label: 'Дата окончания' },
    { key: 'division.name', label: 'Подразделение' },
    { key: 'status', label: 'Проведен' },
  ],
  candidates: [
    { key: 'fullName', label: 'ФИО' },
    { key: 'positionName', label: 'Должность' },
    { key: 'staffPosition.title', label: 'Позиция' },
    { key: 'phone', label: 'Телефон' },
    { key: 'gender', label: 'Пол' },
    { key: 'personType', label: 'Тип ФЛ' },
    { key: 'introducedAt', label: 'Дата введения' },
    { key: 'status', label: 'Статус' },
  ],
  vacancies: [
    { key: 'title', label: 'Наименование' },
    { key: 'staffPosition.title', label: 'Позиция' },
    { key: 'status', label: 'Статус' },
    { key: 'openedAt', label: 'Открыта' },
    { key: 'closedAt', label: 'Закрыта' },
  ],
  relatives: [
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'employee.tabNumber', label: 'Таб. №' },
    { key: 'fullName', label: 'ФИО родственника' },
    { key: 'relation', label: 'Степень родства' },
    { key: 'gender', label: 'Пол' },
    { key: 'birthDate', label: 'Дата рождения' },
    { key: 'workplace', label: 'Рабочее место' },
    { key: 'dependent', label: 'Зависимость' },
    { key: 'phone', label: 'Телефон' },
  ],
  'access-grants': [
    { key: 'employee.lastName', label: 'Сотрудник' },
    { key: 'accessType', label: 'Тип доступа' },
    { key: 'resource', label: 'Ресурс' },
    { key: 'grantedAt', label: 'Выдан' },
    { key: 'expiresAt', label: 'Истекает' },
    { key: 'isActive', label: 'Статус' },
  ],
  'report-templates': [
    { key: 'name', label: 'Название' },
    { key: 'source', label: 'Источник' },
    { key: 'sourceType', label: 'Тип источника' },
    { key: 'fileName', label: 'Файл' },
    { key: 'createdBy', label: 'Создал' },
    { key: 'createdAt', label: 'Дата' },
    { key: 'isActive', label: 'Статус' },
  ],
  'dynamic-fields': [
    { key: 'name', label: 'Динамическое поле' },
    { key: 'dataType', label: 'Тип данных' },
    { key: 'code', label: 'Код' },
    { key: 'isActive', label: 'Статус' },
  ],
  'dynamic-objects': [
    { key: 'name', label: 'Объект' },
    { key: 'code', label: 'Код' },
  ],
};

export function columnsForResource(resource: string): ColumnDef[] | undefined {
  return RESOURCE_COLUMNS[resource];
}
