/** Shared shape for dashboard attendance rows (API + UI). */
export type AttRowLike = {
  employeeId: string;
  id?: string;
  fullName: string;
  lastName?: string;
  firstName?: string;
  middleName?: string | null;
  tabNumber: string;
  photoUrl?: string | null;
  firstIn: string | null;
  lastOut: string | null;
  status: string;
  note?: string;
  email?: string | null;
  phone?: string | null;
  position?: string | null;
  division?: string | null;
  grade?: string | null;
  region?: string | null;
  schedule?: string | null;
  manager?: string | null;
  hiredAt?: string | null;
  birthDate?: string | null;
  gender?: string | null;
  pinfl?: string | null;
  inn?: string | null;
  inps?: string | null;
  code?: string | null;
  addressResidence?: string | null;
  addressPostal?: string | null;
  bankAccount?: string | null;
  employmentType?: string | null;
  workStatus?: string | null;
  login?: string | null;
  telegram?: string | null;
  fax?: string | null;
  site?: string | null;
  fingerprints?: string | null;
  accessLevel?: string | null;
  arrivalLocation?: string | null;
  distanceKm?: number | null;
};
